  // composables/DataTableConfig
  export const tableSetup = {
    //
    // Tables that have selectors need options - or something to define where the options come from....
    // either encode them for each table here, or set a flag/pointer to where they should be.. like:
    // maybe "filterOptions" to cause the dataTable to pull from "filterOptions[datasetKey]" ; will need
    // to know right syntax to abstract the variable that way...
    //
    // NOTE:: the current setup below does not have an alignment prop (for headers or the columns)
    //        also - may want to add an initialSort property
    //
    // NOTE:: Fields may need helperText, per the DataForm editting component
    //        Add 'icon' prop to type=text||textarea||select||multiselect)
    //
    // NOTE:: Adding a 'cols' property will override default (2) in FiltersAndActions composable
    //
    consortia: {
      url: '', dialogTitle: 'Consortium', 
      fields: [
        { name: 'status',      type: 'text', header: true,  editable: true, searchable: false, label: 'Status',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'name',        type: 'text', header: true,  editable: true, searchable: true,  label: 'Consortium Name',
          icon: '', helperText: '' },
        { name: 'displayName', type: 'text', header: false, editable: true, searchable: true,  label: 'Display Name',
          icon: '', helperText: '' },
        { name: 'ccp_key',     type: 'text', header: true,  editable: true, searchable: true,  label: 'Database Key',
          icon: '', helperText: '' },
        { name: 'firstName',   type: 'text', header: false, editable: true, searchable: true,  label: 'First Name',
          icon: '', helperText: '' },
        { name: 'lastName',    type: 'text', header: false, editable: true, searchable: true,  label: 'Last Name',
          icon: '', helperText: '' },
        { name: 'admin_name',  type: 'text', header: true,  editable: true, searchable: true,  label: 'Admin Contact',
          icon: '', helperText: '' },
        { name: 'admin_email', type: 'text', header: true,  editable: true, searchable: true,  label: 'Email Address',
          icon: '', helperText: '' },
      ],
      required: ['name', 'email', 'admin'],
      sortby: 'name',
    },
    institutions: {
      url: '/api/getInsts/admin', dialogTitle: 'Institution',
      fields: [
        { name: 'status',  type: 'toggle',    header: true, editable: true,  searchable: false, label: 'Status',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'name',    type: 'text',      header: true, editable: true,  searchable: true,  label: 'Institution Name',
          icon: '', helperText: '' },
        { name: 'group_string', type: 'text', header: true, editable: false, searchable: true,  label: 'Groups',
          icon: '', helperText: '' },
        { name: 'groups',  type: 'mselect',   header: false, editable: true, searchable: false, label: 'Groups',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '' },
        { name: 'type',    type: 'select',    header: true, editable: true,  searchable: true,  label: 'Institution Type',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '' },
        { name: 'role',    type: 'select',    header: true, editable: false, searchable: true,  label: 'Role',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '' },
      ],
      required: ['name', 'type', 'status'],
      static: ['group_string'],
      sortby: 'name',
    },
    institutionGroups: {
      url: '/api/getInstGroups', dialogTitle: 'Institution Group',
      fields: [
        { name: 'name',         type: 'text',   header: true, editable: true,  searchable: true, label: 'Group',
          icon: '', helperText: '' },
        { name: 'institutions', type: 'mselect', header: false, editable: true, searchable: false, label: 'Member Institutions',
          icon: '', helperText: '' },
        { name: 'count',        type: 'text',   header: true, editable: false, searchable: true, label: 'Member Count',
          icon: '', helperText: '' },
        { name: 'type', type: 'select', header: true, editable: true,  searchable: true, label: 'Institution Type Restriction',
          options: 'fromURL', icon: '', helperText: '' },
      ],
      required: ['name'],
      sortby: 'name',
    },
    institutionTypes: {
      url: '/api/getInstTypes', dialogTitle: 'Institution Type',
      fields:[
        // { title: 'Type Value', key: 'id' },
        { name: 'id',   type: 'number', header: false, editable: false, searchable: false, label: 'ID',
          icon: '', helperText: '' },
        { name: 'name', type: 'text',   header: true,  editable: true,  searchable: true, label: 'Institution Type ',
          icon: '', helperText: '' },
      ],
      required: ['name'],
      static: ['id'],
      sortby: 'name',
    },
    connections: {
      url: '/api/getCreds', dialogTitle: 'Credentials',
      // Report columns are type=select to offer options based on user's role
      fields: [
        { name: 'id',          type: 'number', header: false, editable: false, searchable: false, label: 'ID',
          icon: '', helperText: '' },
        { name: 'platform',    type: 'text',   header: true,  editable: false, searchable: true,  label: 'Platform Name',
          icon: '', helperText: '' },
        { name: 'abbrev',      type: 'text',   header: false, editable: true,  searchable: true,  label: 'Abbreviation',
          icon: '', helperText: '' },
        { name: 'dataHost',    type: 'text',   header: false, editable: true,  searchable: true,  label: 'Data Host',
          icon: '', helperText: '' },
        { name: 'institution', type: 'text',   header: true,  editable: false, searchable: true,  label: 'Institution Name',
          icon: '', helperText: '' },
        { name: 'customerId',  type: 'text',   header: true,  editable: true,  searchable: true,  label: 'Customer ID',
          icon: '', helperText: '' },
        { name: 'requestorId', type: 'text',   header: true,  editable: true,  searchable: true,  label: 'Requestor ID',
          icon: '', helperText: '' },
        { name: 'apiKey',      type: 'text',   header: true,  editable: true,  searchable: true,  label: 'API Key',
          icon: '', helperText: '' },
        { name: 'PR',          type: 'select', header: true,  editable: true,  searchable: false, label: 'PR Report',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'DR',          type: 'select', header: true,  editable: true,  searchable: false, label: 'DR Report',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'TR',          type: 'select', header: true,  editable: true,  searchable: false, label: 'TR Report',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'IR',          type: 'select', header: true,  editable: true,  searchable: false, label: 'IR Report',
          options: 'fromURL', icon: '', helperText: '' },
      ],
      required: ['id'],
      static: ['id'],
      sortby: 'platform',
    },
    platforms: {
      url: '/api/getPlatforms/admin', dialogTitle: 'Platform',
      fields: [
        { name: 'id',            type: 'number',  header: false, editable: false, searchable: false, label: 'ID',
          icon: '', helperText: '' },
        { name: 'status',        type: 'select',  header: true,  editable: true,  searchable: false, label: 'Status',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'name',          type: 'text',    header: true,  editable: true,  searchable: true,  label: 'Platform Name',
          icon: '', helperText: '' },
        { name: 'abbrev',        type: 'text',    header: true,  editable: true,  searchable: true,  label: 'Abbreviation',
          icon: '', helperText: '' },
        { name: 'release',       type: 'mselect', header: true,  editable: true,  searchable: true,  label: 'Release Versions',
          options: ['5.0', '5.1'], icon: '', helperText: '' },
        { name: 'dataHost',      type: 'text',    header: true,  editable: true,  searchable: true,  label: 'Data Host',
          icon: '', helperText: '' },
        { name: 'registryId',    type: 'text',    header: false, editable: true,  searchable: true,  label: 'Registry ID',
          icon: '', helperText: '' },
        { name: 'harvestDate',   type: 'number',  header: true,  editable: true,  searchable: true,  label: 'Harvest Day',
          icon: '', helperText: '' },
        { name: 'cnxcount',      type: 'text',    header: true,  editable: false, searchable: true,  label: 'Connection Count',
          icon: '', helperText: '' },
        { name: 'datetime',      type: 'text',    header: true,  editable: false, searchable: true,  label: 'Last Updated',
          icon: '', helperText: '' },
        { name: 'refreshable',   type: 'text',    header: false, editable: true,  searchable: true,  label: 'Refreshable',
          icon: '', helperText: '' },
      ],
      required: ['name', 'abbrev', 'dataHost'],
      static: ['id'],
      sortby: 'name',
    },
    users: {
      url: '/api/getUsers', dialogTitle: 'User',
      fields:[
        { name: 'id',          type: 'number', header: false, editable: false, searchable: false, label: 'ID',
          icon: '', helperText: '' },
        { name: 'status',      type: 'toggle',   header: true,  editable: true,  searchable: false, label: 'Status',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'name',        type: 'text',     header: true,  editable: true,  searchable: true,  label: 'Username',
          icon: '', helperText: '' },
        { name: 'email',       type: 'text',     header: true,  editable: true,  searchable: true,  label: 'Email Address',
          icon: '', helperText: '' },
        { name: 'institution.name', type: 'text', header: true, editable: false, searchable: true,  label: 'Institution',
          icon: '', helperText: '' },
        { name: 'institutions', type: 'select',  header: false, editable: true,  searchable: false, label: 'Institution',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'password',    type: 'password', header: false, editable: true,  searchable: false, label: 'Password',
          icon: '', helperText: ''},
        { name: 'last_login',  type: 'text',     header: true,  editable: false, searchable: false, label: 'Last Login',
          icon: '', helperText: '' },
      ],
      required: ['name', 'email', 'institutions', 'role'],
      static: ['id', 'institution.name'],
      sortby: 'email',
    },
    roles: {
      url: '/api/getRoles', dialogTitle: 'User Roles',
      fields:[
        { name: 'role_id',   type: 'number', header: false, editable: false, searchable: false, label: 'ID',
          icon: '', helperText: '' },
        { name: 'status',    type: 'toggle', header: true,  editable: true,  searchable: false, label: 'Status',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'name',      type: 'text',   header: true,  editable: false, searchable: true,  label: 'Username',
          icon: '', helperText: '' },
        { name: 'email',     type: 'text',   header: true,  editable: false, searchable: true,  label: 'Email Address',
          icon: '', helperText: '' },
        { name: 'inst_name', type: 'text',   header: true,  editable: false, searchable: true,  label: 'Institution',
          icon: '', helperText: '' },
        { name: 'role',      type: 'role',   header: true,  editable: true,  searchable: true,  label: 'Role',
          icon: '', helperText: '' },
      ],
      required: ['role_id', 'role'],
      static: ['role_id'],
      sortby: 'email',
    },
    harvests: {
      url: '/api/getHarvests', dialogTitle:'',
      fields: [
        { name: 'id',          type: 'number', header: false, editable: false, searchable: false, label: 'ID',
          icon: '', helperText: '' },
        { name: 'updated',     type: 'text',   header: true, editable: false, searchable: true, label: 'Result Date',
          options: ['last hour', 'last day', 'last week'], icon: '', helperText: '' },
        { name: 'prov_name',   type: 'text',   header: true, editable: false, searchable: true, label: 'Platform',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'inst_name',   type: 'text',   header: true, editable: false, searchable: true, label: 'Institution',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'report_name', type: 'text',   header: true, editable: false, searchable: true, label: 'Report',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'yearmon',     type: 'text',   header: true, editable: false, searchable: true, label: 'Usage Date',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'id',          type: 'text',   header: true, editable: false, searchable: true, label: 'Harvest ID'},
        { name: 'errorId',     type: 'text',   header: true, editable: false, searchable: true, label: 'Result',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'status',      type: 'select', header: true, editable: true,  searchable: true, label: 'Status',
          options: 'fromURL', icon: '', helperText: '' },
      ],
      required: [],
      static: ['id'],
      // ASC or DESC??
      sortby: 'updated',
    },
    jobs: {
      url: '/api/getJobs', dialogTitle:'',
      fields: [
        { name: 'id',          type: 'number', header: false, editable: false, searchable: false, label: 'ID',
          icon: '', helperText: '' },
        { name: 'created',     type: 'text',   header: true, editable: false,  searchable: true, label: 'Created',
          icon: '', helperText: ''},
        { name: 'prov_name',   type: 'text',   header: true, editable: false,  searchable: true, label: 'Platform',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'inst_name',   type: 'text',   header: true, editable: false,  searchable: true, label: 'Institution',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'report_name', type: 'text',   header: true, editable: false,  searchable: true, label: 'Report',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'yearmon',     type: 'text',   header: true, editable: false,  searchable: true, label: 'Usage Date',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'id',          type: 'text',   header: true, editable: false,  searchable: true, label: 'Harvest ID',
          icon: '', helperText: ''},
        { name: 'dStatus',     type: 'select', header: true, editable: true,   searchable: true, label: 'Status',
          options: 'fromURL', icon: '', helperText: '' },
      ],
      required: [],
      static: ['id'],
      // ASC or DESC??
      sortby: 'created',
    },
    savedreports: {
      url: '/api/getSavedReports', dialogTitle: 'Saved Report',
      fields: [
        { name: 'id',            type: 'number', header: false, editable: false, searchable: false, label: 'ID',
          icon: '', helperText: '' },
        { name: 'title',         type: 'text',   header: true,  editable: true,  searchable: true, label: 'Report Title',
          icon: '', helperText: ''},
        { name: 'master_name',   type: 'text',   header: true,  editable: false, searchable: true, label: 'Report',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'date_range',    type: 'select', header: true,  editable: true,  searchable: true, label: 'Date Range',
          options: [ { title: 'Fiscal YTD', value: 'fYTD' },
                     { title: 'Prior FY', value: 'priorFy' },
                     { title: 'Calendar YTD', value: 'cYTD' },
                     { title: 'Custom', value: 'Custom' } ], icon: '', helperText: ''
        },
        { name: 'last_harvest',  type: 'text',   header: true,  editable: false, searchable: true, label: 'Last Run Date',
          icon: '', helperText: ''},
        { name: 'format',        type: 'select', header: true,  editable: true,  searchable: true, label: 'Format',
          options: ['Compact', 'COUNTER'], icon: '', helperText: '' },
        { name: 'exclude_zeros', type: 'select', header: true,  editable: true,  searchable: true, label: 'Include Zeros',
          options: ['true', 'false'], icon: '', helperText: '' },
      ],
      required: [],
      static: ['id'],
      sortby: 'title',
    }
};
