  // composables/DataTableConfig
  export const tableSetup = {
    //
    // Tables that have selectors need options - or something to define where the options come from....
    // either encode them for each table here, or set a flag/pointer to where they should be.. like:
    // maybe "filterOptions" to cause the dataTable to pull from "filterOptions[datasetKey]" ; will need
    // to know right syntax to abstract the variable that way...
    //
    // NOTE:: Fields may need helperText, per the DataForm editting component
    //        Add 'icon' prop to type=text||textarea||select||multiselect)
    //
    institutions: {
      urlRoot: '/api/institutions', title: 'Institution',
      fields: [
        { name: 'id',           type: 'number',   header: null,     editable: false, searchable: false, label: 'CC+ System ID',
          icon: '', helperText: '' },
        { name: 'status',       type: 'toggle',   header: 'center', editable: true,  searchable: false, label: 'Status',
          options: 'fromURL', icon: '', helperText: '', addValue: 'Active' },
        { name: 'name',         type: 'text',     header: 'start',  editable: true,  searchable: true,  label: 'Institution Name',
          icon: '', helperText: '' },
        { name: 'local_id',     type: 'text',     header: null,     editable: true,  searchable: true,  label: 'Local ID',
          icon: '', helperText: '' },
        { name: 'group_string', type: 'text',     header: 'start',  editable: false, searchable: true,  label: 'Groups',
          icon: '', helperText: '' },
        { name: 'group_ids',    type: 'array',    header: null,     editable: false, searchable: false, label: 'Group Assigmnent(s)',
          icon: '', helperText: '' },
        { name: 'groups',       type: 'mselect',  header: null,     editable: true,  searchable: false, label: 'Groups',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'group_ids' },
        { name: 'type',         type: 'select',   header: 'start',  editable: true,  searchable: true,  label: 'Institution Type',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'type_id' },
        { name: 'type_id',      type: 'number',   header: null,     editable: false, searchable: false, label: 'Type ID',
          icon: '', helperText: '' },
        { name: 'role',         type: 'text',     header: 'start',  editable: false, searchable: true,  label: 'Role',
          icon: '', helperText: '' },
        { name: 'fte',          type: 'number',   header: null,     editable: true,  searchable: false, label: 'FTE',
          icon: '', helperText: '' },
        { name: 'notes',        type: 'textarea', header: null,     editable: true,  searchable: true,  label: 'Notes',
          icon: '', helperText: '' },
        { name: 'creds',        type: 'toggle',   header: null,     editable: true,  searchable: false,
          label: 'Add Credential Placeholders', options: ['Inactive','Active'], icon: '', helperText: '', addValue: 'Active' },
      ],
      required: ['status', 'name', 'local_id', 'fte', 'type', 'creds'],
      static: ['id','group_string','group_ids','type_id'],
      bulkOptions: ['Set Active', 'Set Inactive', 'Assign Type', 'Create New Group', 'Add to Existing Group'],
      exportFields: ['id','local_id','name','status','fte','group_ids','notes'],
      sortby: 'name',
    },
    types: {
      urlRoot: '/api/types', title: 'Institution Type',
      fields:[
        { name: 'id',   type: 'number', header: null,    editable: false, searchable: false, label: 'ID',
          icon: '', helperText: '' },
        { name: 'name', type: 'text',   header: 'start', editable: true,  searchable: true,  label: 'Institution Type ',
          icon: '', helperText: '' },
      ],
      required: ['name'],
      static: ['id'],
      bulkOptions: [],
      exportFields: ['id','name'],
      sortby: 'name',
    },
    groups: {
      urlRoot: '/api/groups', title: 'Institution Group',
      fields: [
        { name: 'id',           type: 'number',  header: null,     editable: false, searchable: false, label: 'ID',
          icon: '', helperText: '' },
        { name: 'name',         type: 'text',    header: 'start',  editable: true,  searchable: true,  label: 'Group',
          icon: '', helperText: '' },
        { name: 'institutions', type: 'mselect', header: null,     editable: true, searchable: false,  label: 'Member Institutions',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: false },
        { name: 'count',        type: 'text',    header: 'center', editable: false, searchable: true,  label: 'Member Count',
          icon: '', helperText: '' },
        { name: 'type_string', type: 'text', header: 'start', editable: false, searchable: true,
          label: 'Institution Type Restriction', icon: '', helperText: '' },
        { name: 'types', type: 'select', header: null, editable: true, searchable: true, label: 'Institution Type Restriction',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'type_id' },
        { name: 'type_id',      type: 'number',  header: null,     editable: false, searchable: false, label: 'Type ID',
          icon: '', helperText: '', addValue: 1 },
      ],
      required: ['name','institutions'],
      static: ['id','type_id','type_string'],
      bulkOptions: [],
      exportFields: ['id','name'],
      sortby: 'name',
    },
    users: {
      urlRoot: '/api/users', title: 'User',
      fields:[
        { name: 'id',           type: 'number',   header: null,    editable: false, searchable: false, label: 'ID',
          icon: '', helperText: '' },
        { name: 'status',       type: 'toggle',   header: 'center', editable: true,  searchable: false, label: 'Status',
          options: 'fromURL', icon: '', helperText: '', addValue: 'Active' },
        { name: 'name',         type: 'text',     header: 'start', editable: true,  searchable: true,  label: 'User Name',
          icon: '', helperText: '' },
        { name: 'email',        type: 'text',     header: 'start', editable: true,  searchable: true,  label: 'Email Address',
          icon: '', helperText: '' },
        { name: 'phone',        type: 'text',     header: 'null',  editable: true,  searchable: true,  label: 'Phone Number',
          icon: '', helperText: '' },
        { name: 'institution.name', type: 'text', header: 'start', editable: false, searchable: true,  label: 'Home Institution',
          icon: '', helperText: '' },
        { name: 'institutions', type: 'select',   header: null,    editable: true,  searchable: false, label: 'Institution',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'inst_id' },
        { name: 'inst_id',      type: 'number',   header: null,    editable: false, searchable: false, label: 'Institution ID',
          icon: '', helperText: '' },
        { name: 'user_role',    type: 'text',     header: 'start', editable: false, searchable: true,  label: 'Role',
          icon: '', helperText: '' },
        { name: 'uroles',       type: 'text',   header: null,    editable: true,  searchable: false, label: 'Role',
          options: 'fromURL', icon: '', helperText: '', isFilter: true, filterCol: 'user_role' },
        { name: 'inst_roles',   type: 'array',    header: null,    editable: false, searchable: false, label: 'Institutional Role(s)',
          icon: '', helperText: '' },
        { name: 'group_roles',  type: 'array',    header: null,    editable: false, searchable: false, label: 'Group Role(s)',
          icon: '', helperText: '' },
        { name: 'password',     type: 'password', header: null,    editable: true,  searchable: false, label: 'Password',
          icon: '', helperText: ''},
        { name: 'confirm_pass', type: 'passconf', header: null,    editable: true,  searchable: false, label: 'Confirm Password',
          icon: '', helperText: ''},
        { name: 'fiscalYr',     type: 'select',   header: null,    editable: true,  searchable: false, label: 'Fiscal Year Start',
          options: '', optVal: 'label', optTxt: 'label', icon: '', helperText: '' },
        { name: 'last_login',   type: 'text',   header: 'center',  editable: false, searchable: false, label: 'Last Login',
          icon: '', helperText: '' },
      ],
      required: ['status', 'name', 'email', 'institutions', 'password', 'confirm_pass'],
      static: ['id', 'institution.name', 'inst_id', 'uroles', 'inst_roles', 'group_roles'],
      bulkOptions: ['Set Active', 'Set Inactive', 'Delete'],
      exportFields: ['id','email','password','name','phone','status','inst_id','inst_roles','group_roles'],
      sortby: 'email',
    },
    roles: {
      urlRoot: '/api/roles', title: 'Permissions',
      fields:[
        { name: 'role_id',     type: 'number', header: null, editable: false, searchable: false, label: 'role_id',
          icon: '', helperText: '' },
        { name: 'user_id',     type: 'number', header: null, editable: false, searchable: false, label: 'user_id',
          icon: '', helperText: '' },
        { name: 'inst_id',     type: 'number', header: null, editable: false, searchable: false, label: 'inst_id',
          icon: '', helperText: '' },
        { name: 'group_id',    type: 'number', header: null, editable: false, searchconfigable: false, label: 'group_id',
          icon: '', helperText: '' },
        { name: 'name',        type: 'text',   header: 'start',  editable: false, searchable: true,  label: 'Username',
          icon: '', helperText: '' },
        { name: 'email',       type: 'text',   header: 'start',  editable: false, searchable: true,  label: 'Email Address',
          icon: '', helperText: '' },
        { name: 'role_string', type: 'text',   header: 'start',  editable: false, searchable: true,  label: 'Role',
          icon: '', helperText: '' },
        { name: 'scope',       type: 'text',   header: 'start',  editable: false, searchable: true,  label: 'Scope',
          icon: '', helperText: '' },
        { name: 'role',        type: 'text',   header: null, editable: false, searchable: false, label: 'Role',
          options: 'fromURL', icon: '', helperText: '', isFilter: true, filterCol: 'role_string' },
        { name: 'user_role',   type: 'select', header: null, editable: true,  searchable: false, label: 'Role',
          options: 'fromURL', icon: '', helperText: '', isFilter: false },
        { name: 'user',        type: 'select', header: null, editable: true,  searchable: false, label: 'User',
          options: 'fromURL', optVal: 'id',      optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'user_id' },
        { name: 'conso',       type: 'toggle', header: null, editable: true,  searchable: false, label: 'Entire Consortium',
          options: ['Inactive','Active'], icon: '', helperText: '', isFilter: false, addValue: 'Inactive' },
        { name: 'institution', type: 'select', header: null, editable: true,  searchable: false, label: 'Institution',
          options: 'fromURL', optVal: 'id',      optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'inst_id' },
        { name: 'group',      type: 'select', header: null, editable: true,  searchable: false, label: 'Group',
          options: 'fromURL', optVal: 'id',      optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'group_id' },
      ],
      required: ['user_role', 'user', 'conso', 'institution', 'group'],
      static: ['role', 'user_id', 'role_id', 'inst_id', 'group_id'],
      bulkOptions: ['Delete'],
      exportFields: [],
      sortby: 'email',
    },
    connections: {
      urlRoot: '/api/connections', title: 'Connection',
      fields: [
        { name: 'id',        type: 'number',  header: null,     editable: false, searchable: false, label: 'ID',
          icon: '', helperText: '' },
        { name: 'platform',  type: 'text',    header: 'start',  editable: false, searchable: true,  label: 'Platform Name',
          icon: '', helperText: '' },
        { name: 'PR',        type: 'toggle',  header: 'center', editable: true,  searchable: false, label: 'PR Report',
          icon: '', helperText: '' },
        { name: 'pr_insts',  type: 'array',   header: null,     editable: true,  searchable: true,  label: 'PR Institution ID(s)',
          icon: '', helperText: '' },
        { name: 'pr_groups', type: 'array',   header: null,     editable: true,  searchable: true,  label: 'PR Group ID(s)',
          icon: '', helperText: '' },
        { name: 'DR',        type: 'toggle',  header: 'center', editable: true,  searchable: false, label: 'DR Report',
          icon: '', helperText: '' },
        { name: 'dr_insts',  type: 'array',   header: null,     editable: true,  searchable: true,  label: 'DR Institution ID(s)',
          icon: '', helperText: '' },
        { name: 'dr_groups', type: 'array',   header: null,     editable: true,  searchable: true,  label: 'DR Group ID(s)',
          icon: '', helperText: '' },
        { name: 'TR',        type: 'toggle',  header: 'center', editable: true,  searchable: false, label: 'TR Report',
          icon: '', helperText: '' },
        { name: 'tr_insts',  type: 'array',   header: null,     editable: true,  searchable: true,  label: 'TR Institution ID(s)',
          icon: '', helperText: '' },
        { name: 'tr_groups', type: 'array',   header: null,     editable: true,  searchable: true,  label: 'TR Group ID(s)',
          icon: '', helperText: '' },
        { name: 'IR',        type: 'toggle',  header: 'center', editable: true,  searchable: false, label: 'IR Report',
          icon: '', helperText: '' },
        { name: 'ir_insts',  type: 'array',   header: null,     editable: true,  searchable: true,  label: 'IR Institution ID(s)',
          icon: '', helperText: '' },
        { name: 'ir_groups', type: 'array',   header: null,     editable: true,  searchable: true,  label: 'IR Group ID(s)',
          icon: '', helperText: '' },
        { name: 'result',    type: 'text',    header: 'start',  editable: false, searchable: true,  label: 'Last Harvest',
          icon: '', helperText: '' },
        { name: 'results',   type: 'mselect', header: null,     editable: true,  searchable: false, label: 'Last Harvest',
          options: 'fromURL', optVal: 'result', optTxt: 'result', icon: '', helperText: '', isFilter: true, filterCol: 'result' },
        { name: 'conso',     type: 'toggle',  header: null,     editable: true,  searchable: false, label: 'Entire Consortium',
          options: ['Inactive','Active'], icon: '', helperText: '', isFilter: false, addValue: 'Inactive' },
        { name: 'institutions', type: 'mselect', header: null,  editable: true, searchable: false,  label: 'Institution(s)',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: false },
        { name: 'groups',    type: 'mselect', header: null,     editable: true, searchable: false,  label: 'Group(s)',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: false },
      ],
      required: ['id'],
      static: ['id', 'results','institutions', 'groups', 'pr_insts', 'pr_groups', 'dr_insts', 'dr_groups',
               'tr_insts', 'tr_groups', 'ir_insts', 'ir_groups'],
      bulkOptions: [],
      exportFields: ['id', 'platform', 'pr_insts', 'pr_groups', 'dr_insts', 'dr_groups',
                     'tr_insts', 'tr_groups', 'ir_insts', 'ir_groups'],
      sortby: 'platform',
    },
    credentials: {
      urlRoot: '/api/credentials', title: 'Credentials',
      // Report columns are type=select to offer options based on user's role
      fields: [
        { name: 'status',           type: 'toggle', header: 'center', editable: true,  searchable: false, label: 'Status',
          options: '', icon: '', helperText: '', addValue: 'Enabled' },
        { name: 'institutions',     type: 'select', header: null,     editable: false, searchable: false, label: 'Institution',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'inst_id' },
        { name: 'institution',      type: 'text',   header: 'start',  editable: false, searchable: true,  label: 'Institution',
          icon: '', helperText: '' },
        { name: 'inst_id',          type: 'number', header: null,     editable: false, searchable: false, label: 'Institution ID',
          icon: '', helperText: '' },
        { name: 'local_id',         type: 'text',   header: null,     editable: true,  searchable: true,  label: 'Local ID',
          icon: '', helperText: '' },
        { name: 'platforms',        type: 'select', header: null,     editable: false, searchable: false, label: 'Platform',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'prov_id' },
        { name: 'platform',         type: 'text',   header: 'start',  editable: false, searchable: true,  label: 'Platform',
          icon: '', helperText: '' },
        { name: 'prov_id',          type: 'number', header: null,     editable: false, searchable: false, label: 'Platform ID',
          icon: '', helperText: '' },
        { name: 'groups',           type: 'mselect', header: null,    editable: true,  searchable: false, label: 'Group(s)',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: false },
        { name: 'customer_id',      type: 'text',   header: 'start',  editable: true,  searchable: true,  label: 'Customer ID',
          icon: '', helperText: '' },
        { name: 'requestor_id',     type: 'text',   header: 'start',  editable: true,  searchable: true,  label: 'Requestor ID',
          icon: '', helperText: '' },
        { name: 'api_key',          type: 'text',   header: 'start',  editable: true,  searchable: true,  label: 'API Key',
          icon: '', helperText: '' },
        { name: 'PR',               type: 'toggle', header: 'center',  editable: true, searchable: false, label: 'PR Report',
          icon: '', helperText: '' },
        { name: 'DR',               type: 'toggle', header: 'center',  editable: true, searchable: false, label: 'DR Report',
          icon: '', helperText: '' },
        { name: 'TR',               type: 'toggle', header: 'center',  editable: true, searchable: false, label: 'TR Report',
          icon: '', helperText: '' },
        { name: 'IR',               type: 'toggle', header: 'center',  editable: true, searchable: false, label: 'IR Report',
          icon: '', helperText: '' },
        { name: 'statuses',     type: 'mtext',   header: null,    editable: false, searchable: false, label: 'Status',
          options: 'fromURL', icon: '', helperText: '', isFilter: true, filterCol: 'status' },
        { name: 'result',   type: 'text',    header: 'start',  editable: false, searchable: true,  label: 'Last Harvest',
          icon: '', helperText: '' },
        { name: 'results',  type: 'mselect', header: null, editable: true,  searchable: false, label: 'Last Harvest',
          options: 'fromURL', optVal: 'result', optTxt: 'result', icon: '', helperText: '', isFilter: true, filterCol: 'result' },
      ],
      required: ['institutions','platforms','customer_id', 'requestor_id', 'api_key'],
      static: ['groups', 'statuses', 'results', 'inst_id', 'prov_id', 'local_id'],
      bulkOptions: ['Enable', 'Disable', 'Delete'],
      exportFields: ['inst_id', 'local_id', 'institution', 'prov_id', 'platform', 'customer_id', 'requestor_id', 'api_key'],
      sortby: 'platform',
    },
    audit: {
      urlRoot: '/api/audit', title: '',
      fields: [
        { name: 'plat_id',      type: 'number',  header: null,    editable: false, searchable: false, label: 'Platform ID',
          icon: '', helperText: '' },
        { name: 'status',       type: 'toggle',  header: 'start', editable: false, searchable: false, label: 'Credential Status',
          icon: '', helperText: '' },
        { name: 'plat_valid',   type: 'toggle',  header: 'center', editable: true, searchable: false, label: 'Platform Valid',
          options: '', icon: '', helperText: '' },
        { name: 'plat_name',    type: 'text',    header: 'start', editable: false, searchable: true,  label: 'Platform',
          icon: '', helperText: '' },
        { name: 'json_item',    type: 'text',    header: 'start', editable: false, searchable: true,  label: 'JSON Platform Item',
          icon: '', helperText: '' },
        { name: 'json_host',    type: 'text',    header: 'start', editable: false, searchable: true,  label: 'Data Host',
          icon: '', helperText: '' },
        // { name: 'statuses',     type: 'mtext',   header: null,    editable: false, searchable: false, label: 'Status',
        //   options: 'fromURL', icon: '', helperText: '', isFilter: true, filterCol: 'status' },
        { name: 'valid_types',  type: 'text',    header: null,    editable: false, searchable: false, label: 'Validation',
          options: 'fromURL', icon: '', helperText: '', isFilter: true, filterCol: 'valid_state' },
        { name: 'platforms',    type: 'mselect', header: null,    editable: false, searchable: false, label: 'Platform(s)',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'plat_id' },
        { name: 'inst_id',      type: 'number',  header: null,    editable: false, searchable: false, label: 'Institution ID',
          icon: '', helperText: '' },
        { name: 'inst_valid',   type: 'toggle',  header: 'center', editable: true, searchable: false, label: 'Institution Valid',
          options: '', icon: '', helperText: '' },
        { name: 'json_inst',    type: 'text',    header: 'start', editable: false, searchable: true,  label: 'JSON Institution',
          icon: '', helperText: '' },
        { name: 'inst_name',    type: 'text',    header: 'start', editable: false, searchable: true,  label: 'Institution',
          icon: '', helperText: '' },
        { name: 'institutions', type: 'mselect', header: null,    editable: false, searchable: false, label: 'Institution(s)',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'inst_id' },
        { name: 'group_ids',    type: 'array',   header: null,    editable: false, searchable: false, label: 'Group IDs',
          icon: '', helperText: '' },
        { name: 'groups',       type: 'mselect', header: null, editable: true,  searchable: false, label: 'Groups',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'group_ids' },
        { name: 'conso_only',   type: 'toggle',  header: null, editable: false, searchable: false, label: 'Consortium Only',
          options: ['Inactive','Active'], icon: '', helperText: '', isFilter: true, filterCol: 'is_conso' },
        { name: 'no_inst',    type: 'toggle',  header: null, editable: false, searchable: false, label: 'Hide No JSON Institution',
          options: ['Inactive','Active'], icon: '', helperText: '', isFilter: true, filterCol: 'inst_set' },
        { name: 'no_plat',    type: 'toggle',  header: null, editable: false, searchable: false, label: 'Hide No JSON Platform',
          options: ['Inactive','Active'], icon: '', helperText: '', isFilter: true, filterCol: 'plat_set'  },
        { name: 'no_host',    type: 'toggle',  header: null, editable: false, searchable: false, label: 'Hide No JSON DataHost',
          options: ['Inactive','Active'], icon: '', helperText: '', isFilter: true, filterCol: 'host_set' },
        { name: 'json_inst',    type: 'text',    header: null, editable: false, searchable: true,  label: 'JSON Institution',
          options: ['Inactive','Active'], icon: '', helperText: '' },
      ],
      required: [],
      static: ['inst_id', 'plat_id', 'statuses', 'valid_types', 'group_ids'],
      bulkOptions: ['Set Institution Validated', 'Set Platform Validated','Clear Validation'],
      exportFields: ['plat_name','inst_name','json_host','json_item','json_inst'],
      sortby: 'platform',
    },
    jobs: {
      urlRoot: '/api/jobs', title:'',
      fields: [
        { name: 'created',     type: 'text',     header: 'start', editable: false, searchable: true,  label: 'Created',
          icon: '', helperText: ''},
        { name: 'prov_name',   type: 'text',     header: 'start', editable: false, searchable: true,  label: 'Platform',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'inst_name',   type: 'text',     header: 'start', editable: false, searchable: true,  label: 'Institution',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'report_name', type: 'text',     header: 'start', editable: false, searchable: true,  label: 'Report',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'yearmon',     type: 'text',     header: 'start', editable: false, searchable: true,  label: 'Usage Date',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'harvest_id',          type: 'text',     header: 'start', editable: false, searchable: true,  label: 'Harvest ID',
          icon: '', helperText: ''},
        { name: 'd_status',     type: 'text',   header: 'start', editable: false,  searchable: true,  label: 'Status',
          icon: '', helperText: ''},
        { name: 'rawfile',     type: 'text',   header: null,    editable: false, searchable: true, label: 'Raw Datafile',
          icon: '', helperText: '' },
        { name: 'retryUrl',    type: 'text',   header: null,    editable: false, searchable: true, label: 'Retry URL',
          icon: '', helperText: '' },
        { name: 'platforms',    type: 'mselect', header: null,    editable: true,  searchable: false, label: 'Platform(s)',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'prov_id' },
        { name: 'institutions', type: 'mselect', header: null,    editable: true,  searchable: false, label: 'Institution(s)',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'inst_id' },
        { name: 'reports',      type: 'mselect', header: null,    editable: true,  searchable: false, label: 'Report(s)',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'report_id' },
        { name: 'codes',        type: 'mtext', header: null,    editable: true,  searchable: false, label: 'Error Code(s)',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'error_id' },
        { name: 'statuses',     type: 'mselect',   header: null,    editable: true,  searchable: false, label: 'Status(es)',
          options: 'fromURL', optVal: 'value', optTxt: 'text', icon: '', helperText: '', isFilter: true, filterCol: 'status' },
      ],
      required: [],
      static: ['id','rawfile','retryUrl'],
      bulkOptions: ['Pause', 'Restart', 'Kill'],
      exportFields: [],
      sortby: 'created',
    },
    harvests: {
      urlRoot: '/api/harvests', title:'',
      fields: [
        { name: 'updated',     type: 'text',   header: 'start', editable: false, searchable: true, label: 'Result Date',
          icon: '', helperText: '' },
        { name: 'prov_name',   type: 'text',   header: 'start', editable: false, searchable: true, label: 'Platform',
          icon: '', helperText: '' },
        { name: 'release',     type: 'text',   header: 'center', editable: false, searchable: true, label: 'Release',
          icon: '', helperText: '' },
        { name: 'inst_name',   type: 'text',   header: 'start', editable: false, searchable: true, label: 'Institution',
          icon: '', helperText: '' },
        { name: 'report_name', type: 'text',   header: 'center', editable: false, searchable: true, label: 'Report',
          icon: '', helperText: '' },
        { name: 'yearmon',     type: 'text',   header: 'end', editable: false, searchable: true, label: 'Usage Date',
          icon: '', helperText: '' },
        { name: 'harvest_id',  type: 'text',   header: 'end', editable: false, searchable: true, label: 'Harvest ID',
          icon: '', helperText: '' },
        { name: 'error',       type: 'text',   header: 'start', editable: false, searchable: true, label: 'Result',
          icon: '', helperText: '' },
        { name: 'statusDot',   type: 'text',  header: 'center', editable: false, searchable: false, label: 'Status',
          icon: '', helperText: '' },
        { name: 'rawfile',     type: 'text',   header: null,    editable: false, searchable: true, label: 'Raw Datafile',
          icon: '', helperText: '' },
        { name: 'retryUrl',    type: 'text',   header: null,    editable: false, searchable: true, label: 'Retry URL',
          icon: '', helperText: '' },
        { name: 'platforms',    type: 'mselect', header: null,  editable: true,  searchable: false, label: 'Platform(s)',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'prov_id' },
        { name: 'institutions', type: 'mselect', header: null,  editable: true,  searchable: false, label: 'Institution(s)',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'inst_id' },
        { name: 'groups',     type: 'mselect', header: null,    editable: true,  searchable: false, label: 'Institution Group(s)',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'inst_id' },
        { name: 'reports',      type: 'mselect', header: null,  editable: true,  searchable: false, label: 'Report(s)',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'report_id' },
        { name: 'updates',      type: 'text', header: null,     editable: true,  searchable: false, label: 'Updated',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'timeframes' },
        { name: 'yymms',        type: 'mtext', header: null,    editable: true,  searchable: false, label: 'Usage Date(s)',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'yearmon' },
        { name: 'codes',        type: 'mtext', header: null,    editable: true,  searchable: false, label: 'Error Code(s)',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'error_id' },
        { name: 'statuses',     type: 'mtext',   header: null,  editable: true,  searchable: false, label: 'Status(es)',
          options: 'fromURL', optVal: 'id', optTxt: 'name', icon: '', helperText: '', isFilter: true, filterCol: 'd_status' },
      ],
      required: [],
      static: ['id','rawfile','retryUrl'],
      bulkOptions: ['Restart', 'Restart as r5', 'Restart as r5.1', 'Delete'],
      exportFields: [],
      sortby: 'updated',
    },
    savedreports: {
      urlRoot: '/api/savedreports', title: 'Saved Report',
      fields: [
        { name: 'id',            type: 'number', header: null, editable: false, searchable: false, label: 'ID',
          icon: '', helperText: '' },
        { name: 'title',         type: 'text',   header: 'start',  editable: true,  searchable: true, label: 'Report Title',
          icon: '', helperText: ''},
        { name: 'report_name',   type: 'text',   header: 'start',  editable: false, searchable: true, label: 'Report',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'date_range',    type: 'select', header: 'start',  editable: true,  searchable: true, label: 'Date Range',
          options: [ { title: 'Fiscal YTD', value: 'fYTD' },
                     { title: 'Prior FY', value: 'priorFy' },
                     { title: 'Calendar YTD', value: 'cYTD' },
                     { title: 'Custom', value: 'Custom' } ], icon: '', helperText: '', isFilter: true
        },
        { name: 'last_harvest',  type: 'text',   header: 'start',  editable: false, searchable: true, label: 'Last Run Date',
          icon: '', helperText: ''},
        { name: 'format',        type: 'select', header: 'start',  editable: true,  searchable: true, label: 'Format',
          options: ['Compact', 'COUNTER'], icon: '', helperText: '', isFilter: true },
        { name: 'exclude_zeros', type: 'select', header: 'start',  editable: true,  searchable: true, label: 'Include Zeros',
          options: ['true', 'false'], icon: '', helperText: '', isFilter: false },
      ],
      required: [],
      static: ['id'],
      bulkOptions: [],
      exportFields: [],
      sortby: 'title',
    },
    consortia: {
      urlRoot: '/api/consortia', title: 'Consortium', 
      fields: [
        { name: 'status',      type: 'text', header: 'center',  editable: true, searchable: false, label: 'Status',
          options: 'fromURL', icon: '', helperText: '' },
        { name: 'name',        type: 'text', header: 'start',  editable: true, searchable: true,  label: 'Consortium Name',
          icon: '', helperText: '' },
        { name: 'displayName', type: 'text', header: null, editable: true, searchable: true,  label: 'Display Name',
          icon: '', helperText: '' },
        { name: 'ccp_key',     type: 'text', header: 'start',  editable: true, searchable: true,  label: 'Database Key',
          icon: '', helperText: '' },
        { name: 'firstName',   type: 'text', header: null, editable: true, searchable: true,  label: 'First Name',
          icon: '', helperText: '' },
        { name: 'lastName',    type: 'text', header: null, editable: true, searchable: true,  label: 'Last Name',
          icon: '', helperText: '' },
        { name: 'admin_name',  type: 'text', header: 'start',  editable: true, searchable: true,  label: 'Admin Contact',
          icon: '', helperText: '' },
        { name: 'admin_email', type: 'text', header: 'start',  editable: true, searchable: true,  label: 'Email Address',
          icon: '', helperText: '' },
      ],
      required: ['name', 'email', 'admin'],
      static: [],
      bulkOptions: [],
      exportFields: [],
      sortby: 'name',
    },
    platforms: {
      urlRoot: '/api/platforms', title: 'Platform',
      fields: [
        { name: 'id',             type: 'number', header: null,     editable: false, searchable: false, label: 'ID',
          icon: '', helperText: '' },
        { name: 'status',         type: 'toggle', header: 'center', editable: true,  searchable: false, label: 'Status',
          options: '', icon: '', helperText: '', addValue: 'Active' },
        { name: 'name',           type: 'text',    header: 'start',  editable: true,  searchable: true,  label: 'Platform Name',
          icon: '', helperText: '' },
        { name: 'abbrev',         type: 'text',   header: 'start',  editable: true,  searchable: true,  label: 'Abbreviation',
          icon: '', helperText: '' },
        { name: 'cur_release',    type: 'text',   header: 'center', editable: true,  searchable: true,  label: 'Release',
          icon: '', helperText: '' },
        { name: 'is_selected',    type: 'toggle', header: null,     editable: true,  searchable: false, label: 'Status',
          options: '', icon: '', helperText: '' },
        { name: 'reg_releases',   type: 'array',  header: null,     editable: true,  searchable: true,  label: 'COUNTER Releases',
          icon: '', helperText: '' },
        { name: 'releases',       type: 'mtext',  header: null,     editable: false, searchable: true,  label: 'COUNTER Releases',
          options: 'fromURL', icon: '', helperText: '', isFilter: true, filterCol: 'reg_releases' },
        { name: 'service_url',    type: 'text',   header: null,     editable: true,  searchable: true,  label: 'Service URL',
          icon: '', helperText: '' },
        { name: 'data_host',      type: 'text',   header: 'start',  editable: true,  searchable: true,  label: 'Data Host',
          icon: '', helperText: '' },
        { name: 'day_of_month',   type: 'number', header: 'start',  editable: true,  searchable: true,  label: 'Harvest Day',
          icon: '', helperText: '' },
        { name: 'instance_count', type: 'text',   header: 'start',  editable: false, searchable: true,  label: 'Connected Instances',
          icon: '', helperText: '' },
        { name: 'connector_state', type: 'array', header: null, editable: true,  searchable: true,  label: 'Connection Fields',
          icon: '', helperText: '' },
        { name: 'report_state',    type: 'array', header: null, editable: true,  searchable: true,  label: 'Supported Reports',
          icon: '', helperText: '' },
        { name: 'refreshable',    type: 'toggle', header: null,     editable: true,  searchable: false, label: 'Refreshable',
          icon: '', helperText: '', addValue: 'Inactive' },
        { name: 'registry_id',    type: 'text',   header: null,     editable: true,  searchable: false, label: 'Registry ID',
          icon: '', helperText: '' },
        { name: 'platform_parm',  type: 'text',   header: null,     editable: true,  searchable: true,  label: 'Platform Parameter',
          icon: '', helperText: '' },
        { name: 'updated',        type: 'text',   header: 'start',  editable: false, searchable: true,  label: 'Last Updated',
          icon: '', helperText: '' },
        { name: 'refresh_result', type: 'text',   header: null,     editable: false, searchable: true,  label: 'Refresh Result',
          icon: '', helperText: '' },
        { name: 'results',       type: 'mselect', header: null,     editable: false, searchable: true,  label: 'Filter Refresh Result',
          options: 'fromURL', optVal: 'key', optTxt: 'value', icon: '', helperText: '', isFilter: true, filterCol: 'refresh_result' },
        { name: 'statuses',       type: 'text',   header: null,     editable: false, searchable: true,  label: 'Filter Status',
          options: 'fromURL', icon: '', helperText: '', isFilter: true, filterCol: 'status' },
        { name: 'customer_id',    type: 'text', header: null, editable: true, searchable: false, label:'Customer ID',
          icon: '', helperText: '' },
        { name: 'requestor_id',   type: 'text', header: null, editable: true, searchable: false, label:'Requestor ID',
          icon: '', helperText: '' },
        { name: 'api_key',        type: 'text', header: null, editable: true, searchable: false, label:'API Key',
          icon: '', helperText: '' },
        { name: 'refresh_text',   type: 'text', header: null, editable: false, searchable: true, label: 'Refresh Result Tooltip',
          icon: '', helperText: '' },
        { name: 'refresh_icon',   type: 'text', header: null, editable: false, searchable: true, label: 'Refresh Result Icon',
          icon: '', helperText: '' },
        { name: 'refresh_color',  type: 'text', header: null, editable: false, searchable: true, label: 'Refresh ResultColor',
          icon: '', helperText: '' },
      ],
      required: ['name', 'status', 'abbrev', 'cur_release', 'service_url', 'connector_state', 'report_state', 'platform_parm',
                 'day_of_month', 'refreshable', 'registry_id'],
      static: ['id','instance_count','updated','PR','DR','TR','IR','is_selected','reg_releases','customer_id',
               'requestor_id','api_key','connector_state','report_state','data_host','refresh_result','refresh_text',
               'refresh_icon','refresh_color'],
      bulkOptions: ['Set Active', 'Set Inactive', 'Refresh Registry', 'Delete'],
      // These are set by GlobalProviderController export() method
      exportFields: ['registry_id','name','release','status','service_url','refreshable','day_of_month','PR','DR','TR','IR',
                     'customer_id','requestor_id','api_key','platform_parm'],
      sortby: 'name',
    }
};
